export enum AppRoutes {
  Home = '/',
  Login = '/login',
  Register = '/register',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password',
  AnnouncementResultList = '/announcement-result-list',
  NewAnnouncement = '/new-announcement',
  EditAnnouncement = '/edit-announcement',
  MyAnnouncements = '/my-announcements',
  MyProfile = '/my-profile',
  MyProfileChangeData = '/my-profile/change-data',
  MyProfileChangePassword = '/my-profile/change-password',
  MyProfileChangeEmail = '/my-profile/change-email',
  Chat = '/chat',
  MyChats = '/my-chats',
}
